run-dist:
	@./build/install/app/bin/app file1.json file2.json

run-dist-h:
	@./build/install/app/bin/app -h

installDist:
	@./gradlew clean installDist

clean:
	@./gradlew clean

report:
	@./gradlew jacocoTestReport

.PHONY: build